name: linux-arch-release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  linux-arch:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0          # <-- fetch tags

      # Pacman mirrors + refresh ...
      - name: Configure fast mirrors & refresh pacman
        shell: bash
        run: |
          set -euo pipefail
          cat >/etc/pacman.d/mirrorlist <<'EOF'
          Server = https://geo.mirror.pkgbuild.com/$repo/os/$arch
          Server = https://mirror.pkgbuild.com/$repo/os/$arch
          Server = https://mirrors.edge.kernel.org/archlinux/$repo/os/$arch
          EOF
          pacman -Sy --noconfirm archlinux-keyring
          pacman -Syyu --noconfirm --disable-download-timeout

      - name: Install build dependencies
        shell: bash
        run: |
          pacman -S --noconfirm --needed \
            base-devel git curl wget ca-certificates \
            nodejs npm \
            gtk3 webkit2gtk libsoup3 libayatana-appindicator librsvg

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Install frontend deps
        run: npm ci

      # <<< NEW: sync package.json version to Git tag (v0.1.4 -> 0.1.4)
      - name: Set app version from tag
        if: startsWith(github.ref, 'refs/tags/')
        run: npm version --no-git-tag-version "${GITHUB_REF_NAME#v}"

      - name: Generate Tauri icons (if missing)
        shell: bash
        run: |
          if [ ! -f "src-tauri/icons/icon.ico" ]; then
            npx --yes @tauri-apps/cli@^1 icon src-tauri/icons/app-icon.png
          fi

      - name: Build frontend
        run: npm run build

      - name: Tauri build (AppImage)
        env:
          CARGO_TARGET_DIR: ${{ github.workspace }}/target
          NO_STRIP: "1"
          LINUXDEPLOY_NO_STRIP: "1"
        run: npx tauri build --bundles appimage -v

      - name: Preview bundle dir
        if: always()
        run: |
          if [ -d "target/release/bundle" ]; then
            find target/release/bundle -maxdepth 3 -type f -printf "%p (%k KB)\n"
          else
            echo "target/release/bundle does not exist"
          fi

      - name: Find AppImage
        id: find_img
        shell: bash
        run: |
          FILE="$(find target/release/bundle/appimage -type f -name "*.AppImage" | head -n1 || true)"
          if [ -z "$FILE" ]; then
            echo "No AppImage found." >&2
            exit 1
          fi
          echo "path=$FILE" >> "$GITHUB_OUTPUT"
          echo "Found: $FILE"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-appimage
          path: ${{ steps.find_img.outputs.path }}

      - name: Publish GitHub Release (attach AppImage)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
          files: ${{ steps.find_img.outputs.path }}
