name: linux-release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:
    inputs:
      version:
        description: "Semver (e.g., 1.0.0). If empty, uses latest tag."
        required: false
        type: string

jobs:
  linux-appimage:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      # Tauri v2 deps
      - name: Install Linux deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            libsoup-3.0-dev \
            patchelf

      - name: Install frontend deps
        run: npm ci

      - name: Compute APP_VERSION
        env:
          INPUT_VERSION: ${{ inputs.version }}
        run: |
          set -euo pipefail
          if [[ "${GITHUB_REF:-}" == refs/tags/* ]]; then
            ver="${GITHUB_REF_NAME#v}"
          elif [[ -n "${INPUT_VERSION}" ]]; then
            ver="${INPUT_VERSION}"
          else
            ver="$(git describe --tags --abbrev=0 | sed -E 's/^v//')"
          fi
          echo "APP_VERSION=$ver" >> "$GITHUB_ENV"
          echo "Version: $ver"

      - name: Write version override for Tauri
        run: echo "{\"version\":\"${APP_VERSION}\"}" > tauri-version.json

      - name: Generate Tauri icons (if missing)
        run: |
          if [ ! -f "src-tauri/icons/icon.ico" ]; then
            npx --yes @tauri-apps/cli@^2 icon src-tauri/icons/app-icon.png
          fi

      - name: Build & publish (AppImage)
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tauriScript: npx @tauri-apps/cli@^2
          args: --bundles appimage --config tauri-version.json
          tagName: ${{ github.ref_name }}
          releaseName: "AssetTracker v${{ env.APP_VERSION }}"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: false
          prerelease: false
