name: linux-flatpak-release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-flatpak:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      # Build frontend on host (we'll embed these assets when cargo builds inside Flatpak)
      - name: Install deps & build frontend
        run: |
          npm ci
          npm run build

      - name: Install Flatpak & Builder
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder libarchive-tools
          flatpak --version

      # Use user remotes/runtimes to avoid system permission errors
      - name: Add Flathub & install runtimes/SDK
        run: |
          flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak --user install -y flathub org.gnome.Platform//47 org.gnome.Sdk//47
          # Rust toolchain extension (try current, fall back to previous)
          flatpak --user install -y flathub org.freedesktop.Sdk.Extension.rust-stable//24.08 || \
          flatpak --user install -y flathub org.freedesktop.Sdk.Extension.rust-stable//23.08

      - name: Build Flatpak repo (compile inside SDK)
        run: |
          flatpak-builder --user --force-clean \
            --repo=flatpak-repo flatpak-build-dir \
            flatpak/com.github.mackenzie779.assettracker.yml

      - name: Inspect Flatpak refs (debug)
        run: |
          ostree refs --repo=flatpak-repo

      - name: Create single-file .flatpak
        run: |
          VER="${GITHUB_REF_NAME#v}"
          APP_ID="com.github.mackenzie779.assettracker"
          flatpak build-bundle flatpak-repo "AssetTracker_${VER}_x86_64.flatpak" "$APP_ID" \
            --arch=x86_64 \
            --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo
          ls -lh AssetTracker_*_x86_64.flatpak

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-flatpak
          path: AssetTracker_*_x86_64.flatpak

      - name: Attach to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: AssetTracker_*_x86_64.flatpak
