name: linux-release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  linux-appimage:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed so tags are available

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      # System dependencies for Tauri v2 on Ubuntu 24.04
      - name: Install Linux deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            libsoup-3.0-dev \
            patchelf

      - name: Install frontend deps
        run: npm ci

      # Sync package.json version from tag (v0.1.4 -> 0.1.4),
      # works with your tauri.conf.json: "version": "../package.json"
      - name: Set app version from tag
        if: startsWith(github.ref, 'refs/tags/')
        run: npm version --no-git-tag-version "${GITHUB_REF_NAME#v}"

      # Optional: generate icons if missing
      - name: Generate Tauri icons (if missing)
        run: |
          if [ ! -f "src-tauri/icons/icon.ico" ]; then
            npx --yes @tauri-apps/cli@^2 icon src-tauri/icons/app-icon.png
          fi

      # Build & publish with the official action (simplest)
      - name: Build & publish (AppImage)
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tauriScript: npx @tauri-apps/cli@^2
          args: --bundles appimage
          tagName: ${{ github.ref_name }}
          releaseName: "AssetTracker ${{ github.ref_name }}"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: false
          prerelease: false
