name: windows-release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0          # <-- fetch tags

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Install NSIS
        run: choco install nsis -y

      - name: Add NSIS to PATH
        shell: pwsh
        run: |
          foreach ($p in @(
            'C:\Program Files (x86)\NSIS\Bin',
            'C:\Program Files\NSIS\Bin',
            'C:\ProgramData\chocolatey\bin'
          )) { if (Test-Path $p) { echo $p >> $env:GITHUB_PATH } }

      - name: Verify NSIS
        shell: pwsh
        run: |
          $cmd = Get-Command makensis -ErrorAction SilentlyContinue
          if (-not $cmd) { throw "NSIS (makensis) not on PATH" }
          makensis -VERSION

      - name: Install frontend deps
        run: npm ci

      # <<< NEW: sync package.json version to Git tag (v0.1.4 -> 0.1.4)
      - name: Set app version from tag
        if: startsWith(github.ref, 'refs/tags/')
        shell: pwsh
        run: |
          $ver = $env:GITHUB_REF_NAME -replace '^v',''
          npm version --no-git-tag-version $ver

      - name: Generate Tauri icons (if missing)
        shell: pwsh
        run: |
          if (!(Test-Path 'src-tauri\icons\icon.ico')) {
            npx --yes "@tauri-apps/cli@^1" icon "src-tauri/icons/app-icon.png"
          }

      - name: Build frontend
        run: npm run build

      - name: Tauri build (NSIS)
        env:
          CARGO_TARGET_DIR: ${{ github.workspace }}\target
        run: npx tauri build --bundles nsis -v

      - name: Preview bundle dir (debug)
        if: always()
        shell: pwsh
        run: |
          if (Test-Path 'target\release\bundle') {
            Get-ChildItem -Recurse target\release\bundle | Format-Table Length, FullName
          } else {
            Write-Host "target\release\bundle does not exist"
          }

      - name: Find NSIS setup
        id: find_nsis
        shell: pwsh
        run: |
          $file = Get-ChildItem -Recurse -File -Path 'target\release\bundle' -Include '*-setup.exe' | Select-Object -First 1
          if (-not $file) { throw "NSIS setup exe not found under target\release\bundle" }
          "path=$($file.FullName -replace '\\','/')" >> $env:GITHUB_OUTPUT
          Write-Host "Found NSIS: $($file.FullName)"

      - name: Upload artifacts (installer)
        uses: actions/upload-artifact@v4
        with:
          name: windows-bundles
          path: ${{ steps.find_nsis.outputs.path }}

      - name: Publish GitHub Release (attach installer)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
          files: ${{ steps.find_nsis.outputs.path }}
