name: windows-release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: (Windows) Install NSIS for bundling
        run: choco install nsis -y

      - name: Install frontend deps
        run: npm ci
    
      - name: Generate Tauri icons (if missing)
        shell: pwsh
        run: |
            if (!(Test-Path 'src-tauri\icons\icon.ico')) {
            npx --yes "@tauri-apps/cli@^1" icon "src-tauri/icons/app-icon.png"
            }

      - name: Build frontend
        run: npm run build

      - name: Tauri build (NSIS)
        env:
            CARGO_TARGET_DIR: target
        run: npm run tauri:build -- --bundles nsis -v

      - name: Preview bundle dir
        shell: pwsh
        run: Get-ChildItem -Recurse src-tauri\target\release\bundle | Format-Table Length, FullName

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
            name: windows-bundles
            path: |
                target/release/bundle/nsis/*.exe
                target/release/bundle/nsis/*.zip

      # Uncomment this block if you prefer artifacts instead of a Release
      # - name: Upload Windows bundles (no GitHub Release)
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: windows-bundles
      #     path: |
      #       target\release\bundle\nsis\*.exe
