name: windows-release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: (Windows) Install NSIS for bundling
        run: choco install nsis -y

      # verify NSIS is usable; if this fails, bundling would be skipped
      - name: Verify NSIS
        shell: pwsh
        run: |
          if (-not (Get-Command makensis -ErrorAction SilentlyContinue)) {
            throw "NSIS (makensis) not on PATH"
          }
          makensis -VERSION

      - name: Install frontend deps
        run: npm ci

      - name: Generate Tauri icons (if missing)
        shell: pwsh
        run: |
          if (!(Test-Path 'src-tauri\icons\icon.ico')) {
            npx --yes "@tauri-apps/cli@^1" icon "src-tauri/icons/app-icon.png"
          }

      - name: Build frontend
        run: npm run build

      # force predictable output under ./target/
      - name: Tauri build (NSIS)
        env:
          CARGO_TARGET_DIR: target
        run: npm run tauri:build -- --bundles nsis -v

      # 🔎 robust preview: don't fail if a path is missing
      - name: Preview bundle dir(s)
        shell: pwsh
        run: |
          foreach ($d in @('target\release\bundle','src-tauri\target\release\bundle')) {
            Write-Host "`n== $d =="
            if (Test-Path $d) { Get-ChildItem -Recurse $d | Format-Table Length, FullName }
            else { Write-Host "$d does not exist" }
          }

      # 📦 upload installers from either location
      - name: Upload NSIS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-bundles
          path: |
            **/bundle/nsis/*-setup.exe
            **/bundle/nsis/*.nsis.zip
          if-no-files-found: error

      # (optional) also upload the raw exe in case bundling was skipped
      - name: Upload raw exe (fallback)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: windows-raw-exe
          path: |
            target/release/*.exe
            src-tauri/target/release/*.exe
          if-no-files-found: warn
